### ISSUE TITLE
Does not work with MOVE plugin

### ISSUE THREAD

**Issue by u07** [flammy/imagebox#116]
Could you please update it to make compatible with the move plugin? Now when we rename images, the links are not updated if handled by ImageBox.

See here: https://github.com/michitux/dokuwiki-plugin-move/issues/156

**Comment by schniepp** [comment]
I noticed the same problem. 

Since imagebox amends the syntax, there is no way that the move plugin can find the links in the imagebox syntax. I think to fix this, the move plugin would have to be amended to also recognize and update links in imageboxes, for cases in which both plugins are installed.

**Comment by flammy** [comment]
thank you for your contribution, the pr is merged.
